<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="https://tinhih.com/assets/media/logos/Logo.png">
    <title>TiNHiH Portal - API Documentation</title>
    <meta property="og:title" content="TiNHiH Portal API – Fast & Scalable API Solutions">
    <meta property="og:description"
        content="TiNHiH.com API offers seamless, secure, and scalable integration for developers. Enhance your applications with powerful endpoints and automation.">
    <meta property="og:image" content="{{ asset('assets/logos/api.jpg') }}">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://tinhih.com">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="TiNHiH.com API – Fast & Scalable API Solutions">
    <meta name="twitter:description"
        content="TiNHiH.com API offers seamless, secure, and scalable integration for developers. Enhance your applications with powerful endpoints and automation.">
    <meta name="twitter:image" content="{{ asset('assets/logos/api.jpg') }}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.19.0/swagger-ui.css"
        integrity="sha512-Fx2bx472ykst5EwyqNnGgXC2pPBxuxRnxHSa5Elf7sVbYA1vj2M/J50eJ0aXDal5hDjdSl3EEaQCaO5y69HmcQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.19.0/swagger-ui-bundle.js"
        integrity="sha512-LxH0xceBKDaKjWgAB0LArdehzzNQ+XsFZaag+UVP43WOXjRFgd/LTQGfuWj4gfMy9mzHl/nyBTteU4+MOJKyvw=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.19.0/swagger-ui-standalone-preset.js"
        integrity="sha512-cwJgSc5T8oJ8eE+iXwRTaVUeM1Ickjzb4NE7uSJ78rzD/3PzbuOHmKGlDvSRDNvo3T5zWzuVw4FNbOCVPMukPA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>

<body>
    <div id="swagger-ui"></div>
    <script>
        const ui = SwaggerUIBundle({
            url: "/api/docs", // Path to your API documentation generated by Swagger-PHP
            dom_id: '#swagger-ui',
            deepLinking: true,
            presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIBundle.SwaggerUIStandalonePreset
            ]
        });
    </script>
</body>

</html>