<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>API Documentation - {{ env('APP_NAME') }}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.19.0/swagger-ui.css"
        integrity="sha512-Fx2bx472ykst5EwyqNnGgXC2pPBxuxRnxHSa5Elf7sVbYA1vj2M/J50eJ0aXDal5hDjdSl3EEaQCaO5y69HmcQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.19.0/swagger-ui-bundle.js"
        integrity="sha512-LxH0xceBKDaKjWgAB0LArdehzzNQ+XsFZaag+UVP43WOXjRFgd/LTQGfuWj4gfMy9mzHl/nyBTteU4+MOJKyvw=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.19.0/swagger-ui-standalone-preset.js"
        integrity="sha512-cwJgSc5T8oJ8eE+iXwRTaVUeM1Ickjzb4NE7uSJ78rzD/3PzbuOHmKGlDvSRDNvo3T5zWzuVw4FNbOCVPMukPA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>

<body>
    <div id="swagger-ui"></div>
    <script>
        const ui = SwaggerUIBundle({
            url: "/api/docs", // Path to your API documentation generated by Swagger-PHP
            dom_id: '#swagger-ui',
            deepLinking: true,
            presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIBundle.SwaggerUIStandalonePreset
            ]
        });
    </script>
</body>

</html>
